// Generated by CoffeeScript 1.6.3
var gp;

gp = require('../utils/data_helpers').GP;

exports.main_page = function(req, res) {
  var results;
  results = [];
  gp(req.db, 1, function(data, args) {
    results.push([args[0], data]);
    if (results.length === 1) {
      console.log(results);
      return res.render('index', {
        'res': results
      });
    }
  });
};
